
env = Environment()
env.Append(CXXFLAGS=['-std=c++14'])
env.Append(CPPDEFINES=['NO_GODOT'])
env.ParseConfig('pkg-config --libs --cflags miral mirserver')
env.Program(target='mir_shell_bin', source=Glob('*.cpp') + Glob('*/*.cpp'))
